name: simplysubi
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8836
title: simply suBi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcddde'
    - '#1e8fb0'
    - '#58707e'
    - '#000000'
    - '#92b2c6'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
